export const cuisineList = [
  "Waakye",
  "Jollof Rice",
  "Banku & Tilapia",
  "Fufu & Light Soup",
  "Kelewele",
  "Kebab/Suya",
  "Kokonte",
  "Kenkey & Fish",
  "Rice Balls",
  "TZ (Tuo Zaafi)",
  "Fried Plantain",
  "Palm Nut Soup",
  "Groundnut Soup",
  "BBQ",
  "Vegetarian",
];
